spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # drop table 후 create table
    properties:
      hibernate:
        # '[show_sql]': true  # System.out 에 하이버네이트 실행 SQL을 남김. 운영환경에서 부적절
        '[format_sql]': true

logging:
  level:
    '[org.hibernate.SQL]': debug  # logger를 통해 하이버네이트 실행 SQL을 남김.
    '[org.hibernate.orm.jdbc.bind]': trace